spring.application.name=Web_DATN
server.port=${PORT:8081}

# SMTP Configuration (Set environment variables MAIL_USERNAME and MAIL_PASSWORD on Render)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true